# technomancer-ros-dev:jazzy
ARG BASE_IMAGE=technomancer-ros-base:jazzy
FROM ${BASE_IMAGE}

USER root
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install -y --no-install-recommends \
    clang clangd clang-format cmake gdb lldb ninja-build \
    python3-pytest python3-opencv python3-numpy python3-yaml \
    ros-${ROS_DISTRO}-rviz2 \
    ros-${ROS_DISTRO}-rqt* \
    ros-${ROS_DISTRO}-navigation2 \
    ros-${ROS_DISTRO}-nav2-bringup \
    ros-${ROS_DISTRO}-moveit \
    ros-${ROS_DISTRO}-ros2-control \
    ros-${ROS_DISTRO}-ros2-controllers \
    ros-${ROS_DISTRO}-image-transport \
    ros-${ROS_DISTRO}-vision-msgs \
    && rm -rf /var/lib/apt/lists/*
USER tm
WORKDIR /workspace
CMD ["bash"]
